### ISSUE TITLE
Project Metabug: Kill Breakpad

### ISSUE THREAD

**Issue by Gankra** [getsentry/symbolic#375]
High-level goal: improve [rust-minidump](https://github.com/luser/rust-minidump/) to the point that it can replace all the uses of [breakpad](https://github.com/google/breakpad) in Sentry and Firefox.

For now this should be restricted to the scope of: 

* x64, ARM64, (x86?)
* Windows, Android, MacOS, Linux, (iOS?)

Subtasks (many of these should get their own bugs, but here's my initial sketch of what I know):

* [ ] Ensure rust-minidump can parse and expose all the minidump details we rely on
    * [ ] TODO: investigate major missing features to flesh out this list
    * [ ] Use MiscInfo5 to get extended XSAVE CpuContexts
    * [ ] Extract the [GetLastError](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror) value from each thread's TEB

* [ ] Replace the derlict breakpad-symbols subcrate with a new symbolication implementation
    * [ ] Integrate `symbolic` into rust-minidump (plan TBD)
    * [ ] Support grabbing symbols for local system libraries on crashing clients? (drivers!)
    * [ ] Support grabbing symbols from a symbol server

* [ ] Complete implementations of the various unwinding info formats:
    * [ ] Potentially migrate symbolic-minidump's logic into rust-minidump? (vaguely mentioned)
    * [ ] Potentially create a new binary intermediate representation to replace breakpad's text format
        * [ ] Double-check if the binary breakpad format is right for this (would rather not by default)
    * [ ] Implement PDB Exception Tables (done?)
        * [ ] [ARM64 windows is special](https://github.com/mozilla/dump_syms/issues/5)?
    * [ ] Implement DWARF CFI (done?)
    * [ ] MacOS Compact Unwind Info
        * [ ] land base impl in symbolic
            * [ ] upstream into goblin?
        * [ ] ARM64 opcodes
        * [ ] x86/x64 Stack-Indirect opcodes(?) (don't seem to occur in firefox)
        * [ ] extract personality / lsda(?) (only needed for full runtime unwinding)

* [ ] Implement an (offline) unwinder
    * [ ] Potentially make a new independent crate for this, instead of being in minidump-processor
    * [ ] ARM stack walker
        * [ ] Scanning
        * [ ] Frame-pointer-based
        * [ ] CFI-based
    * [ ] x86/x64 stack walker
        * [ ] Scanning (In Review)
        * [ ] Frame-pointer-based (In Review)
        * [ ] CFI-based
    * [ ] Major stretchgoals (don't block on these but keep them in mind):
        * [ ] Can handle native debuginfo formats (for local system symbols)
        * [ ] Can run online (function as replacement for libunwind)
            * [ ] Can implement the [backtrace-rs](https://github.com/rust-lang/backtrace-rs) usecase
            * [ ] Can implement the `panic!` usecase (handling personality/lsdas to run dtors, catch_panic)
            * [ ] nostd compatible (don't allocate!)

* [ ] Implement client-side minidump generation ([Bugzilla#1588530](https://bugzilla.mozilla.org/show_bug.cgi?id=1588530))
    * [ ] Can invoke native windows minidump APIs
    * [ ] Can generate fake minidump on Linux
        * [ ] Integrate [minidump_writer_linux](https://github.com/msirringhaus/minidump_writer_linux/)
    * [ ] Can generate fake minidump on MacOS
    * [ ] Can generate fake minidump on Android

--------------

# The Context

Minidumps are a Microsoft-designed format for more compact dumps of a process's state when it crashes, notably including full memory dumps of every thread's stacks/registers and mapped code modules (libraries that are linked in and what addresses they were mapped to).

Windows has native APIs for generating minidumps, but this is a feature that's desirable on other platforms, so google-breakpad was created to generate "fake" minidumps on other platforms and process them all uniformly. The most important output of this process is backtraces for every thread, but additional context stored in minidumps may be useful for debugging weird stuff like "the user's antivirus DLL-injected itself into out process and messed everything up" or "oh look the last syscall failed right before we crashed".

Both Firefox and Sentry rely on breakpad for minidump generation and handling. Unfortunately, breakpad is written in dangerous C++ and basically abandoned by google. Mozilla doesn't bother upstreaming our patches anymore, and it's too much work to maintain it.

# Usecases 

Here's the places where we use breakpad now that should work with a replacement:

* On the server-side, Mozilla uses breakpad in [minidump-stackwalk](https://github.com/mozilla-services/minidump-stackwalk) to process crash reports for [socorro](https://crash-stats.mozilla.org/).

* On the client-side, Mozilla uses breakpad in our [crash-reporter](https://searchfox.org/mozilla-central/source/toolkit/crashreporter) to generate minidumps. For content-process (~tab) crashes, the main process does this work out-of-crashing-process. For main-process (full browser) crashes, the main-process does this work in-crashing-process. Ideally we would have a separate crash-reporting process on the side that monitors the others so that all our handling can be out-of-crashing-process.

* On the client-side, Mozilla uses breakpad in our [minidump-analyzer](https://searchfox.org/mozilla-central/source/toolkit/crashreporter/minidump-analyzer/minidump-analyzer.cpp) to try to analyze the contents of the minidump using the client machine's knowledge of its own system libraries and any local debuginfo we ship with firefox. This allows us to get more accurate symbolication/unwinding. (This also includes some of our own adhoc symbolication/unwinding code which is [Buggy](https://bugzilla.mozilla.org/show_bug.cgi?id=1372830)) and ideally would be replaced

* As a stretch-goal, this work would ideally also replace the need for [moz-stackwalk](https://searchfox.org/mozilla-central/source/mozglue/misc/StackWalk.cpp) (our own runtime backtracer for debug build backtraces and profiler probing) and [fix-stacks](https://github.com/mozilla/fix-stacks) (cleans up moz-stackwalk's output using native symbols).

* Sentry uses breakpad for its own minidump handling (client-side, server-side?) -- someone from sentry should flesh this out.

# Current Roadmap

Mozilla would like to first get the minidump-stackwalk usecase working, as it's the simplest but also very high traffic (performance matters), and processing user-provided data on our servers (security matters).

minidump-stackwalk only needs to handle pre-processed symbols from our symbol servers (i.e. [the breakpad text format](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/symbol_files.md)), and is operating completely offline from where the minidump was generated. 

The hardest part will be generating backtraces for all the threads, which requires a complete offline unwinder.

**Comment by gabrielesvelto** [comment]
Under the first point we could add making rust-minidump print out as many error codes as possible in a readable format. We have patches on top of breakpad in bug [1704034](https://bugzilla.mozilla.org/show_bug.cgi?id=1704034) and bug [1703248](https://bugzilla.mozilla.org/show_bug.cgi?id=1703248). There's another one coming in bug [1705018](https://bugzilla.mozilla.org/show_bug.cgi?id=1705018) which would give complete coverage of Windows errors. The goal here would be to make all crash exception codes and `GetLastError()` values readable.

**Comment by gabrielesvelto** [comment]
Also yeah, AArch64/Windows unwinding information is special mostly because it didn't match Microsoft documentation. There were quite a few holes and errors that Nathan had to fill when he implemented it. Our implementation in bug [1529355](https://bugzilla.mozilla.org/show_bug.cgi?id=1529355) is probably the gold standard for it.

**Comment by Gankra** [comment]
One thing I didn't have a chance to mention in the meeting: does anyone know if [gimli's dead unwind-rs](https://github.com/gimli-rs/unwind-rs) has any meat to extract for our purposes? 

See also: 

* [symbolic-minidump's stackwalker](https://github.com/getsentry/symbolic/blob/master/symbolic-minidump/src/processor.rs)
* [my WIP stackwalker in breakpad-processor](https://github.com/luser/rust-minidump/pull/145)

Need to read through the former to get a sense of what to salvage from both our impls.

**Comment by Gankra** [comment]
Oh fun the profiling team has *another* unwinder for linux and android64: https://blog.mozilla.org/jseward/2014/05/13/lul-a-lightweight-unwinder-library-for-profiling-gecko/

**Comment by gabrielesvelto** [comment]
On the topic of forked-Breakpad-parity Steven Michaud just added code to read and write macOS-specific `__crash_info` structures, see bug [1577886](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=1577886). rust-minidump would only need the "reading" part since the "writing" one is part of the exception handler and minidump writer.

**Comment by luser** [comment]
A few notes:

> * [ ]  TODO: investigate major missing features to flesh out this list

https://github.com/luser/rust-minidump/issues/22 is one. https://github.com/luser/rust-minidump/issues/25 would be another, but it's a big chunk of work. Probably OK to punt on it for a first pass.

> * [ ]  Support grabbing symbols from a symbol server

https://github.com/jrmuizel/pdb-downloader


> * [ ]  Potentially create a new binary intermediate representation to replace breakpad's text format
>   
>   * [ ]  Double-check if the binary breakpad format is right for this (would rather not by default)

Yeah, don't do that. I think the right thing to do is to move `minidump-processor` over to using `symbolic` directly. Then you could use its symcache format for this.

**Comment by gabrielesvelto** [comment]
> [luser/rust-minidump#22](https://github.com/luser/rust-minidump/issues/22) is one. [luser/rust-minidump#25](https://github.com/luser/rust-minidump/issues/25) would be another, but it's a big chunk of work. Probably OK to punt on it for a first pass.

Yeah those are just busywork. I'll probably tackle them myself in the coming months while I wait for builds and tests to complete.

**Comment by Gankra** [comment]
I think next week I'm going to start trying to rewrite minidump-stackwalk in rust just to properly use rust-minidump in anger and feel out what it's actually missing, and potentially get some preliminary performance numbers.

**Comment by Swatinem** [comment]
> Yeah, don't do that. I think the right thing to do is to move `minidump-processor` over to using `symbolic` directly. Then you could use its symcache format for this.

Another goal that we have is to revise the symcache format btw.
There are some long standing issues related to too conservative limits and other bugs.

In the end, integrating a compact and fast format for CFI is another goal. IMO, apples compact unwind format is a good inspiration, and I will catch up on https://blog.mozilla.org/jseward/2013/09/03/how-compactly-can-cfiexidx-stack-unwinding-info-be-represented/ as well.

**Comment by luser** [comment]
> I think next week I'm going to start trying to rewrite minidump-stackwalk in rust just to properly use rust-minidump in anger and feel out what it's actually missing, and potentially get some preliminary performance numbers.

FWIW, [the `minidump_stackwalk` binary](https://github.com/luser/rust-minidump/blob/d4562d55acc60bd8f102e17b46344fcca81bd715/minidump-processor/src/bin/minidump_stackwalk.rs) in the `minidump-processor` crate is pretty well modeled after the one in Breakpad (as you can tell). The simplest path to success there would be to pull in `serde` and make `ProcessState` serializable so you could write it out to JSON that matches the Socorro implementation (which I also wrote, naturally, so happy to answer any questions on that).

**Comment by Gankra** [comment]
> The simplest path to success there would be to pull in serde and make ProcessState serializable so you could write it out to JSON that matches the Socorro implementation (which I also wrote, naturally, so happy to answer any questions on that).

So I roughed that out but the socorro format and the ProcessState's structure differ a fair amount as far as a naive `derive(Serialize)` goes. To what extent is it reasonable to warp the structure of the crate to match the desired output for Firefox's specific tooling? (Of course, we can write manual serialize impls, but at that point I don't know if there's much benefit over just having all the JSON writing logic in minidump-stackwalk itself.)

**Comment by willkg** [comment]
I (Socorro maintainer) am happy to change Socorro as needed. If it turns out there are scripts downstream for Socorro that need a certain structure, Socorro's processor can deal with supporting and migrating them.

**Comment by Gankra** [comment]
I've made a metabug to specifically track what's needed for the first milestone: https://github.com/luser/rust-minidump/issues/153

**Comment by luser** [comment]
> So I roughed that out but the socorro format and the ProcessState's structure differ a fair amount as far as a naive `derive(Serialize)` goes. To what extent is it reasonable to warp the structure of the crate to match the desired output for Firefox's specific tooling? (Of course, we can write manual serialize impls, but at that point I don't know if there's much benefit over just having all the JSON writing logic in minidump-stackwalk itself.)

That's fair. I don't have a real answer here. The existing `ProcessState` API is mostly a direct port from Breakpad. The Socorro JSON format was intentionally designed to contain all the information we thought would be useful to display in Socorro. The `minidump-processor` APIs haven't had any real-world usage outside of the binaries in my repo, AFAIK, so you should feel free to redesign them in any way you deem suitable.

**Comment by gabrielesvelto** [comment]
> I (Socorro maintainer) am happy to change Socorro as needed. If it turns out there are scripts downstream for Socorro that need a certain structure, Socorro's processor can deal with supporting and migrating them.

Something just occurred to me while I was thinking about the JSON output. Unfortunately Socorro is not the only downstream user. The [minidump-analyzer](https://searchfox.org/mozilla-central/source/toolkit/crashreporter/minidump-analyzer) which we run on user machines also emits Socorro-like JSON but with all the redundant fields stripped away. It's a subset basically. The generated stack trace is sent via crash pings and [documented here](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/crash-ping.html#stack-traces).

This format **has** downstream users: Jim Mathies wrote a tool to symbolicate the crash pings and used Socorro's signature generation library to aggregate crash pings, see [here](http://www.mathies.com/mozilla/crashes/).

**Comment by gabrielesvelto** [comment]
And here's another thought I had in the context of the minidump-analyzer. Since we ship it on user machines it currently contains a lot of redundant code because Breakpad is all or nothing. For example we have to ship ARM unwinding support even in binaries that only run on x86 machines (and thus process only x86 minidumps).

If support for the various architectures and debuginfo formats could be chosen at compile time it would make the binaries quite a bit smaller.

Note this isn't a feature request, it's more like wishful thinking for when everything else will have already been done.

**Comment by willkg** [comment]
It's possible that no one is looking at the minidump-related parts of crash pings other than Jimm's team. They're using [fx-crash-sig](https://github.com/mozilla/fx-crash-sig) (which I maintain) to take a crash ping, symbolicate it with Tecken (which I maintain), and run signature generation on it using [siggen](https://github.com/willkg/socorro-siggen/) (which I maintain). So I can probably handle some amount of change depending on the details. Even so, @gabrielesvelto is right in that it's harder to absorb changes in the crash ping structure than what minidump-stackwalk generates that Socorro consumes.

**Comment by Gankra** [comment]
We've made a lot of progress, so I've taken the opportunity to cleanup the metabug description and marked off everything that's done! We're getting surprisingly close to completing Milestone 1!

I've also given every usecase a proper **bold label** so that subtasks can more clearly indicate that they are only needed for a particular usecase.

**Comment by luser** [comment]
Awesome work, everyone!
