### ISSUE TITLE
Next major version bump

### ISSUE THREAD

**Issue by relaxolotl** [getsentry/symbolic#550]
This is a tracking issue for the breaking changes that are going to trigger a major version bump in an upcoming release of symbolic. In other words, this'll be tracking a group of changes which will change symbolic's public API.

A lot of these are related to the recent switch to using rust-minidump as the stackwalking backend, and therefore it would make sense to bundle them together in one single release instead of incrementally introducing them (this should also reduce version churn as well).

- [x] Add a lifetime to symcache's Transformer and the SymcacheWriter (#544)
- [x] Allow Transformers to mutate themselves when they are performing a transformation (#509)
- [x] Remove `processor` feature in symbolic-minidump
- [x] Remove breakpad from symbolic-minidump
- [x] Rename symbolic-minidump to symbolic-cfi
- [x] Remove symbolic-unwind (Indirectly completing #335, which is directly "solved" by the recent switch to rust-minidump)

**Clean up SymCache**
- [x] Gate `SymCache::functions behind feature` (#548)
- [x] Adjust symcache errors (#552)
- [x] Remove the old symcache
- [x] Reorganize tests
